# Generated by Django 2.2.5 on 2019-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190914_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profilepicture',
            field=models.ImageField(default=None, upload_to='profileimages/'),
        ),
    ]
