# Generated by Django 2.2.5 on 2019-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190914_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='numberofpatients',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
