# Generated by Django 2.2.4 on 2019-09-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_modeltworeport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasNotification', models.BooleanField(default=False)),
                ('msg', models.CharField(max_length=200)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Patient')),
            ],
        ),
    ]
