# Generated by Django 2.2.4 on 2019-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='msg',
            field=models.CharField(max_length=400),
        ),
    ]
