# Generated by Django 2.2.4 on 2019-09-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190914_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Doctor'),
        ),
    ]
